apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webui-{{version}}
  labels:
    app: webui
    version: {{version}}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: webui
      version: {{version}}
  template:
    metadata:
      labels:
        app: webui
        version: {{version}}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      imagePullSecrets:
      - name: registry-webui
      containers:
      - name: main
        image: {{image}}
        imagePullPolicy: Always
        args:
        - --aggregator
        - aggregator:11000
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 8080
