apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webui
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /{{path}}/.*
        backend:
          serviceName: webui
          servicePort: 8080
